# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2025
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "ğŸ¥"
subtitle = "å¤‡æˆ˜ç¬¬ä¸‰å±Šæ•°å­¦èŠ‚çš„å»ºæ¨¡æ¯”èµ›ing"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[article]
headingAnchor = false
math = true
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "HeyuanMiddleSchoolModelingTeam/website"
repoID = "R_kgDOP9sADw"
category = "Announcements"
categoryID = "DIC_kwDOP9sAD84CwWEl"
mapping = "pathname"
lightTheme = "preferred_color_scheme"
darkTheme = "preferred_color_scheme"
reactionsEnabled = 1
emitMetadata = 0
lang = "zh-CN"

# <script src="https://giscus.app/client.js"
#         data-repo="HeyuanMiddleSchoolModelingTeam/website"
#         data-repo-id="R_kgDOP9sADw"
#         data-category="Announcements"
#         data-category-id="DIC_kwDOP9sAD84CwWEl"
#         data-mapping="pathname"
#         data-strict="0"
#         data-reactions-enabled="1"
#         data-emit-metadata="0"
#         data-input-position="bottom"
#         data-theme="preferred_color_scheme"
#         data-lang="zh-CN"
#         crossorigin="anonymous"
#         async>
# </script>
